"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import jsPDF from "jspdf";

interface Report {
  id: string;
  title: string;
  description: string;
  company: string;
  dataUsage: string;
  createdAt: string;
}

const mockReports: Report[] = [
  {
    id: "1",
    title: "Facebook Data Usage Report",
    description: "Your data has been used for targeted advertising.",
    company: "Facebook",
    dataUsage: "Targeted Advertising, Behavioral Analysis",
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Google Data Usage Report",
    description: "Your data is being used to personalize search results.",
    company: "Google",
    dataUsage: "Search Personalization, Ad Targeting",
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Amazon Data Usage Report",
    description:
      "Your shopping preferences were used to suggest similar products.",
    company: "Amazon",
    dataUsage: "Product Recommendation, Purchase History Analysis",
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Netflix Data Usage Report",
    description:
      "Your watch history is being used to suggest movies and TV shows.",
    company: "Netflix",
    dataUsage: "Content Recommendations, Watch History Tracking",
    createdAt: new Date().toISOString(),
  },
];

export default function Reports() {
  const [reports, setReports] = useState<Report[]>(mockReports);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    const fetchReports = async () => {
      try {
        setTimeout(() => {
          setReports(mockReports);
          setLoading(false);
        }, 1000);
      } catch (err) {
        setError("Failed to fetch reports");
        setLoading(false);
      }
    };

    fetchReports();
  }, []);

  const downloadPDF = (report: Report) => {
    const doc = new jsPDF();
    doc.text(report.title, 10, 10);
    doc.text(`Company: ${report.company}`, 10, 20);
    doc.text(report.description, 10, 30);
    doc.text(`Data Usage: ${report.dataUsage}`, 10, 40);
    doc.text(
      `Created at: ${new Date(report.createdAt).toLocaleDateString()}`,
      10,
      50
    );
    doc.save(`${report.title}.pdf`);
  };

  if (loading) return <p>Loading reports...</p>;
  if (error) return <p>Error: {error}</p>;

  return (
    <main className="flex flex-col items-center justify-between p-4 min-w-screen">
      <div className="max-w-[800px] w-full">
        <h1 className="text-4xl font-bold mb-4 dark:text-gray-200">
          Your Data Reports
        </h1>
        <p className="text-sm text-gray-700 dark:text-gray-400 mb-6">
          Below are reports generated by companies based on how your data is
          being used.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {reports.length > 0 ? (
            reports.map((report) => (
              <div
                key={report.id}
                className="bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded-lg shadow-md p-4 transition-transform transform hover:scale-105"
              >
                <h2 className="text-2xl font-semibold dark:text-gray-100">
                  {report.title}
                </h2>
                <p className="mt-2 text-gray-600 dark:text-gray-300">
                  {report.description}
                </p>
                <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  Company: {report.company}
                </p>
                <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  Data Usage: {report.dataUsage}
                </p>
                <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  Created at: {new Date(report.createdAt).toLocaleDateString()}
                </p>
                <Button
                  className="mt-4 w-full"
                  onClick={() => downloadPDF(report)}
                >
                  Download PDF
                </Button>
              </div>
            ))
          ) : (
            <p>No reports found.</p>
          )}
        </div>
      </div>
    </main>
  );
}
